Traceback (most recent call last):
  File "/Volumes/vrona_SSD/FHE.Chess/src/new_model_src_new/magic_chess.py", line 72, in <module>
    train_valid(model, train_loader, valid_loader, criterion_from, criterion_to)
  File "/Volumes/vrona_SSD/FHE.Chess/src/new_model_src_new/trainvalidtest.py", line 83, in train_valid
    output = model(data)
  File "/Users/mikehatchi/anaconda3/envs/fhe_chess/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Volumes/vrona_SSD/FHE.Chess/src/new_model_src_new/chess_cnn.py", line 65, in forward
    x = self.input_layer(x)
  File "/Users/mikehatchi/anaconda3/envs/fhe_chess/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/mikehatchi/anaconda3/envs/fhe_chess/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/Users/mikehatchi/anaconda3/envs/fhe_chess/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [200, 6, 3, 3], expected input[64, 12, 8, 8] to have 6 channels, but got 12 channels instead
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)
(12, 8, 8)